export type Tone = 'rose'|'olive'|'gold'|'plum'|'blue'|'clay';
export type ProgressScene = 'race'|'sailing';
export type Phase = 'setup'|'choosing'|'acquiring'|'reading'|'planning_meeting'|'meeting'|'rating'|'archived'|'paused';
export type PlacedSticker = { id:string; key:string; x:number; y:number; r:number; s:number; z:number };
export type ProfileStyle = { palette?:'paper'|'rose'|'olive'|'gold'|'plum'|'blue'; layout?:'editorial'|'scrapbook'|'clean'; note?:string; stickers?:PlacedSticker[]; wallpaperUrl?:string; avatarUrl?:string };
export type Profile = { id:string; displayName:string; username?:string; avatarUrl?:string; style?:ProfileStyle };
export type Book = { id:string; title:string; author:string; coverUrl?:string; description?:string; pages?:number; year?:number; isbn?:string };
export type Club = { id:string; name:string; ownerId:string; tone:Tone; phase:Phase; inviteCode?:string; coverImageUrl?:string; memberCount:number; progressScene?:ProgressScene };
export type Member = Profile & { role:string; chapter?:number; page?:number; percent?:number; status?:string; format?:string };
export type SuggestedReadingPlan = { generatedAt?:string; durationDays?:number; checkpointCount?:number; basis?:'chapters'|'pages'|'duration'; total?:number; checkpoints?:Array<{day:number;targetChapter?:number;targetPage?:number;progressPercent?:number}> };
export type ClubBook = { id:string; clubId:string; book:Book; status:string; startDate?:string; targetFinishDate?:string; totalChapters?:number; totalPages?:number; suggestedReadingPlan?:SuggestedReadingPlan; suggestedBy?:Profile };
export type Meeting = { id:string; startsAt:string; checkpointId?:string; meetingType?:string; meetingUrl?:string; response?:'going'|'maybe'|'cant'; status?:string };
export type MeetingOption = { id:string; startsAt:string; checkpointId?:string; availableCount:number; myAvailable:boolean };
export type Reply = { id:string; postId:string; userId:string; body:string; createdAt:string; author?:Profile };
export type Reaction = { id?:string; postId:string; userId:string; reaction:string; createdAt?:string };
export type Thought = { id:string; userId:string; body:string; type:string; chapter?:number; createdAt:string; author?:Profile; reactions?:Reaction[]; replyItems?:Reply[]; savedForMeeting?:boolean; predictionRevealed?:boolean };
export type Checkpoint = { id:string; dueAt:string; targetChapter?:number; targetPage?:number; label?:string };
export type CheckpointCheckin = { checkpointId:string; userId:string; status:'reached'|'catching_up'|'not_yet'; updatedAt:string };
export type MarginItem = { id:string; kind:'note'|'quote'; body:string; note?:string; chapter?:number; page?:number; createdAt:string };
export type ClubRating = { rating:number; review?:string; recommend?:boolean };
export type MeetingQuestion = { id:string; postId?:string; body:string; createdAt:string; addedBy?:Profile };
export type Workspace = {
  club:Club;
  members:Member[];
  currentBook?:ClubBook;
  ideaBooks:ClubBook[];
  meeting?:Meeting;
  meetingOptions:MeetingOption[];
  thoughts:Thought[];
  checkpoints:Checkpoint[];
  checkpointCheckins:CheckpointCheckin[];
  acquired:number;
  myProgress?:{chapter?:number; page?:number; percent?:number; status?:string; format?:string};
  archiveBooks:Book[];
  myClubRating?:ClubRating;
  lockedPostCount:number;
  meetingQuestions:MeetingQuestion[];
};

export type AppNotification = { id:string; clubId?:string; type:string; title:string; body?:string; deepLink?:string; readAt?:string; createdAt:string; bookCoverUrl?:string };
