import { useState } from 'react';
import { Plus, LockKeyhole, ChevronRight, Copy, Users, Palette } from 'lucide-react';
import { books, type Club } from '../data/demo';
import { Modal } from '../components/Modal';
export function ClubsPage({clubs,activeClub,onSelect,onCreate}:{clubs:Club[];activeClub:Club;onSelect:(c:Club)=>void;onCreate:(c:Club)=>void}){
 const [mode,setMode]=useState<'create'|'join'|null>(null); const [name,setName]=useState(''); const [code,setCode]=useState(''); const [tone,setTone]=useState<Club['tone']>('pink'); const [mark,setMark]=useState('✣'); const [message,setMessage]=useState('');
 const done=(msg:string)=>{setMessage(msg);setMode(null);setName('');setCode('');setTimeout(()=>setMessage(''),2500)};
 const createClub=()=>{
  const clean=name.trim(); if(!clean) return;
  const newClub:Club={id:`club-${Date.now()}`,name:clean,mark,tone,status:'Just created · finish setup',members:['neha'],phase:'setup',inviteCode:Math.random().toString(36).slice(2,8).toUpperCase()};
  onCreate(newClub); setMode(null); setName('');
 };
 return <div className="page"><header className="title-head"><div><div className="section-label"><LockKeyhole size={13}/> PRIVATE TO YOU</div><h1>Your Clubs</h1></div><button className="round-action" onClick={()=>setMode('create')} aria-label="Start a book club"><Plus/></button></header><p className="lede">Switching clubs changes your whole home screen. Only clubs you belong to appear here.</p>{message&&<div className="toast-inline">{message}</div>}<div className="club-list">{clubs.map(c=>{const b=books.find(x=>x.id===c.bookId)!;return <button className={`club-row ${activeClub.id===c.id?'active-club':''}`} key={c.id} onClick={()=>onSelect(c)}><div className={`club-row-mark ${c.tone}`}>{c.mark}</div><img src={b.cover}/><div><h2>{c.name}</h2><p>{b.title}</p><span>{c.status}</span></div><ChevronRight/></button>})}</div><div className="split-actions"><button className="primary" onClick={()=>setMode('create')}>Start a book club</button><button className="secondary" onClick={()=>setMode('join')}>Join with invite</button></div>
 <Modal open={mode==='create'} onClose={()=>setMode(null)} title="Start a book club"><p className="modal-lede">Create a private space, set its personality, then invite your people.</p><label className="form-label">Club name</label><input className="form-input" value={name} onChange={e=>setName(e.target.value)} placeholder="College Friends"/><label className="form-label"><Palette size={14}/> Accent palette</label><div className="palette-grid">{(['pink','butter','olive','lavender','sky','wine'] as const).map(t=><button key={t} className={`${t} ${tone===t?'selected':''}`} onClick={()=>setTone(t)} aria-label={t}/>)}</div><label className="form-label">Club mark</label><div className="mark-grid">{['✣','✦','♥','★','☻','✿'].map(x=><button key={x} className={mark===x?'selected':''} onClick={()=>setMark(x)}>{x}</button>)}</div><div className="privacy-callout"><LockKeyhole size={18}/><div><b>Invite-only</b><span>Only members can see the club or its activity.</span></div></div><button className="primary full-button" disabled={!name.trim()} onClick={createClub}>Create club</button></Modal>
 <Modal open={mode==='join'} onClose={()=>setMode(null)} title="Join with invite"><p className="modal-lede">Paste an invite code or link from a friend.</p><label className="form-label">Invite code</label><div className="inline-input"><input className="form-input" value={code} onChange={e=>setCode(e.target.value)} placeholder="7LQ9K"/><Copy size={17}/></div><button className="primary full-button" disabled={!code.trim()} onClick={()=>done('Invite accepted. Welcome to the club.')}>Join club</button><div className="privacy-callout"><Users size={18}/><div><b>No discovery directory</b><span>You can only join via a direct invite.</span></div></div></Modal></div>
}
