import { useMemo, useState } from 'react';
import { CalendarDays, ChevronRight, MessageCircle, ArrowUpRight, Pencil, CheckCircle2, Clock3, Settings2, LockKeyhole, Download, PauseCircle, BookOpen, Video, CircleHelp, Vote, Sparkles, Unlock, Check, BellRing, Share2 } from 'lucide-react';
import { books, members, thoughts, type Club } from '../data/demo';
import { ClubStrip } from '../components/ClubStrip';
import { TopBar } from '../components/TopBar';
import { Modal } from '../components/Modal';

export function HomePage({club,openReading,openFriend,openThought,onInvite,onNotifications,onProfile,onSwitchClub,onVote,onSearch}:{club:Club;openReading:()=>void;openFriend:(id:string)=>void;openThought:()=>void;onInvite:()=>void;onNotifications:()=>void;onProfile:()=>void;onSwitchClub:()=>void;onVote:()=>void;onSearch:()=>void}){
 const current=books.find(b=>b.id===club.bookId)??books[0];
 const [progressOpen,setProgressOpen]=useState(false); const [chapter,setChapter]=useState(club.id==='sunday'?12:8); const [format,setFormat]=useState('Physical'); const [dnf,setDnf]=useState(false);
 const [rsvpOpen,setRsvpOpen]=useState(false); const [rsvp,setRsvp]=useState<'going'|'maybe'|'cant'|'unset'>('going'); const [settings,setSettings]=useState(false); const [paused,setPaused]=useState(false); const [notif,setNotif]=useState('Essential'); const [gotCopy,setGotCopy]=useState(false); const [meetingMode,setMeetingMode]=useState(false); const [poll,setPoll]=useState(''); const [recap,setRecap]=useState(false); const [shared,setShared]=useState(false);
 const pct=Math.min(100,Math.round(chapter/26*100));
 const phaseCopy=useMemo(()=>club.phase==='setup'?'New club':club.phase==='choosing'?'Voting is open':club.phase==='meeting'?'Meeting tonight':club.phase==='acquiring'?'Getting our copies':club.phase==='rating'?'Rate the book':'Currently reading',[club.phase]);
 const shareThought=async()=>{try{if(navigator.share) await navigator.share({title:`${current.title} · ${club.name}`,text:'Maya · Chapter 9\n“I genuinely do not trust Mrs. Danvers for one second.”',url:location.href});else await navigator.clipboard?.writeText(location.href);setShared(true);setTimeout(()=>setShared(false),1400)}catch{}};
 if(club.phase==='setup') return <div className={`page home-page club-tone-${club.tone}`}><TopBar club={club} onClubSwitch={onSwitchClub} onNotifications={onNotifications} onProfile={onProfile}/><div className="club-home-tools"><ClubStrip onFriend={openFriend} onInvite={onInvite}/><button className="icon-btn" onClick={()=>setSettings(true)} aria-label="Club settings"><Settings2 size={18}/></button></div><section className={`new-club-setup tone-${club.tone}`}><div className="new-club-confetti">{club.mark}</div><div className="section-label">YOUR NEW CLUB IS READY</div><h1>{club.name}</h1><p>Get your people in here, put a few books on the table, and make the first pick.</p><div className="setup-steps"><button onClick={onInvite}><span>01</span><div><b>Invite your friends</b><small>Share the private invite link.</small></div><ArrowUpRight/></button><button onClick={onSearch}><span>02</span><div><b>Build the idea pile</b><small>Search covers and save possibilities.</small></div><ArrowUpRight/></button><button onClick={onVote}><span>03</span><div><b>Start the first vote</b><small>Pick the first book together.</small></div><ArrowUpRight/></button></div><div className="setup-note"><LockKeyhole size={16}/><span>Private by default · only invited members can see this club.</span></div></section></div>;
 return <div className={`page home-page club-tone-${club.tone}`}><TopBar club={club} onClubSwitch={onSwitchClub} onNotifications={onNotifications} onProfile={onProfile}/><div className="club-home-tools"><ClubStrip onFriend={openFriend} onInvite={onInvite}/><button className="icon-btn" onClick={()=>setSettings(true)} aria-label="Club settings"><Settings2 size={18}/></button></div>
  <section className={`hero-current colorful-hero tone-${club.tone}`}><div className="hero-wash hero-wash-pink"/><div className="hero-wash hero-wash-butter"/><div className="home-kicker">{club.mark} {phaseCopy}</div><div className="current-layout"><div className="cover-object"><img className="hero-cover" src={current.cover}/><span className="cover-tab">{chapter}</span></div><div className="current-copy"><h1>{current.title}</h1><p className="book-author">by <em>{current.author}</em></p>
   {club.phase==='choosing'?<><p className="hero-state-copy">Your club is choosing its next read. Voting closes tomorrow.</p><button className="primary" onClick={onVote}>Vote now <ArrowUpRight size={16}/></button></>:club.phase==='acquiring'?<><p className="hero-state-copy">4 of 5 people have a copy. Once everyone checks in, the reading plan can start.</p><button className={`primary ${gotCopy?'done-button':''}`} onClick={()=>setGotCopy(true)}>{gotCopy?<><CheckCircle2 size={16}/> I have it</>:<>I got my copy <BookOpen size={16}/></>}</button>{gotCopy&&<div className="collective-moment">EVERYONE HAS IT. <span>Set the finish date →</span></div>}</>:club.phase==='meeting'?<><div className="meeting-tonight"><span>TONIGHT</span><b>{club.meeting}</b><p>6 saved questions · 2 predictions · 1 unresolved poll</p></div><button className="primary" onClick={()=>setMeetingMode(true)}><Video size={16}/> Open Meeting Mode</button></>:<><button className="progress-edit" onClick={()=>setProgressOpen(true)}><span>{dnf?'You stopped here':`You’re on Chapter ${chapter}`}</span><b>{pct}%</b><Pencil size={14}/></button><div className="progress"><i style={{width:`${pct}%`}}/></div><div className="unlock-payoff"><Unlock size={15}/><span><b>4 new thoughts</b> are safe for you now.</span></div><button className="primary" onClick={openReading}>Open Reading Room <ArrowUpRight size={16}/></button></>}</div></div><span className="doodle heart">♡</span><span className="doodle starburst">✦</span></section>

  <section className="for-you-section"><div className="section-row"><div><span className="section-label">FOR YOU</span><h2>Three tiny things.</h2></div><span className="for-you-time">~ 1 min</span></div><div className="for-you-list"><button onClick={()=>setProgressOpen(true)}><span className="task-mark olive"><Check size={15}/></span><div><b>Update where you are</b><span>Chapter {chapter} · unlocks spoiler-safe posts</span></div><ChevronRight/></button><button onClick={()=>setRsvpOpen(true)}><span className="task-mark butter"><CalendarDays size={15}/></span><div><b>Sunday at 8?</b><span>{rsvp==='going'?'You said yes · tap to change':'RSVP for FaceTime'}</span></div><ChevronRight/></button><button onClick={openReading}><span className="task-mark petal"><Unlock size={15}/></span><div><b>4 things unlocked</b><span>2 thoughts · 1 prediction · 1 question</span></div><ChevronRight/></button></div><p className="caught-up-copy">When this is empty, you’re done. Go read.</p></section>

  {club.phase==='reading'&&<section className="quiet-section pace-strip"><div><span className="section-label">NEXT CHECKPOINT</span><strong>Chapter 14 · Sunday</strong></div><button className="text-btn" onClick={openReading}>View reading plan →</button></section>}
  {club.phase==='reading'&&chapter<13&&<section className="catchup-card"><Sparkles/><div><span className="section-label">PREVIOUSLY…</span><h2>Pick up where you left off.</h2><p>A spoiler-safe refresher through Chapter {chapter}, plus the people and details worth remembering.</p></div><button className="secondary" onClick={()=>setRecap(true)}>Recap through Ch. {chapter}</button></section>}
  {club.phase!=='choosing'&&club.phase!=='acquiring'&&<section className="quiet-section meeting-section"><div className="meeting-accent"/><div className="section-label">UPCOMING MEETING</div><button className="meeting-row meeting-button" onClick={()=>setRsvpOpen(true)}><CalendarDays/><div><strong>{club.meeting||'Sunday, Sep 22 · 8:00 PM'}</strong><span>FaceTime · tap to RSVP</span></div><div className="mini-avatars">{members.slice(0,4).map(m=><img key={m.id} src={m.avatar}/>)}</div><span className="meeting-count">{rsvp==='cant'?'4 / 6 going':'5 / 6 going'} <ChevronRight size={15}/></span></button></section>}
  <section className="quiet-section activity-section"><div className="section-row"><div><span className="section-label">UNLOCKED FOR YOU</span><h2 className="activity-title">What your friends were thinking.</h2></div><button className="text-btn" onClick={openReading}>See all</button></div>{thoughts.slice(0,2).map(t=>{const m=members.find(x=>x.id===t.user)!;return <div className="activity-row-wrap" key={t.id}><button className="activity-row" onClick={openReading}><img src={m.avatar}/><div><strong>{m.name} · Chapter {t.chapter}</strong><span>{t.text}</span></div><time>{t.ago}</time><ChevronRight size={16}/></button><button className="share-thought" onClick={shareThought} aria-label="Share thought"><Share2 size={15}/></button></div>})}<button className="floating-thought" onClick={openThought}><MessageCircle size={19}/> I have a thought</button>{shared&&<div className="toast-inline">Shared link ready</div>}</section>
  <section className="club-shelf-preview"><div className="section-row"><div><span className="section-label">CLUB ARCHIVE</span><h2>Our shelf</h2></div><span className="archive-count">8 books together</span></div><div className="archive-books">{[books[4],books[2],books[3],books[5],books[6]].map((b,i)=><button key={b.id} onClick={openReading}><span>0{i+1}</span><img src={b.cover}/></button>)}</div><div className={`archive-plank ${club.tone}`}/><div className="annual-tease"><span>VOLUME I · 2026</span><b>A year of books, meetings, bad predictions, and very specific opinions.</b><button className="text-btn">Preview annual →</button></div></section>

  <Modal open={progressOpen} onClose={()=>setProgressOpen(false)} title="Update your progress"><p className="modal-lede">Where are you in {current.title}?</p><div className="format-pills">{['Physical','Kindle','Apple Books','Audiobook'].map(f=><button key={f} className={format===f?'selected':''} onClick={()=>setFormat(f)}>{f}</button>)}</div><div className="chapter-picker"><button onClick={()=>setChapter(Math.max(1,chapter-1))}>−</button><div><b>Chapter {chapter}</b><span>{pct}% complete · {format}</span></div><button onClick={()=>setChapter(chapter+1)}>+</button></div><input aria-label="Chapter" type="range" min="1" max="26" value={chapter} onChange={e=>setChapter(Number(e.target.value))}/><div className="unlock-preview"><Unlock size={17}/><div><b>{chapter>=12?'4':'2'} posts unlock here</b><span>They’ll appear as soon as you save.</span></div></div><button className="dnf-button" onClick={()=>setDnf(v=>!v)}>{dnf?'Continue reading':'I’m done with this book (DNF)'}</button><button className="primary full-button" onClick={()=>setProgressOpen(false)}>Save progress</button></Modal>
  <Modal open={recap} onClose={()=>setRecap(false)} title={`Previously in ${current.title}`}><div className="recap-sheet"><span className="section-label">THROUGH CHAPTER {chapter}</span><p className="recap-big">You’re still settling into Manderley. The narrator is increasingly aware that Rebecca’s presence shapes the house even when nobody says her name.</p><div className="recap-people"><b>People worth remembering</b><span>Maxim · Mrs. Danvers · Frank Crawley</span></div><div className="recap-last"><span>YOUR LAST THOUGHT</span><p>“I don’t trust Mrs. Danvers.”</p></div></div><button className="primary full-button" onClick={()=>{setRecap(false);openReading()}}>Back to the book</button></Modal>
  <Modal open={rsvpOpen} onClose={()=>setRsvpOpen(false)} title="Are you coming?"><p className="modal-lede">{club.meeting||'Sunday, Sep 22 · 8:00 PM'} · FaceTime</p><div className="rsvp-grid">{([['going','I’m going',CheckCircle2],['maybe','Maybe',Clock3],['cant','Can’t make it',CalendarDays]] as const).map(([id,label,Icon])=><button key={id} className={rsvp===id?'selected':''} onClick={()=>setRsvp(id)}><Icon/><span>{label}</span></button>)}</div>{rsvp==='cant'&&<textarea className="absence-note" placeholder="Leave a hot take or question for the meeting (optional)…"/>}<button className="primary full-button" onClick={()=>setRsvpOpen(false)}>Save RSVP</button></Modal>
  <Modal open={settings} onClose={()=>setSettings(false)} title={`${club.name} settings`}><div className="privacy-callout"><LockKeyhole size={18}/><div><b>Private club</b><span>Only these members can view its books, posts, meetings, and archive.</span></div></div><div className="settings-list"><article><span>How we choose</span><b>Everyone votes</b></article><article><span>Cadence</span><b>Monthly-ish</b></article><article><span>Usual meeting</span><b>Sunday evenings</b></article><article><span>Reading pace</span><b>Relaxed</b></article></div><label className="form-label">Notifications</label><div className="format-pills">{['Essential','Social','Quiet'].map(n=><button key={n} className={notif===n?'selected':''} onClick={()=>setNotif(n)}>{n}</button>)}</div><button className="secondary full-button" onClick={()=>setPaused(v=>!v)}><PauseCircle size={16}/> {paused?'Resume club':'Pause reminders'}</button><button className="text-btn export-button"><Download size={15}/> Export club archive</button></Modal>
  <Modal open={meetingMode} onClose={()=>setMeetingMode(false)} title="Meeting mode"><div className="meeting-mode-head"><span>{current.title}</span><span>5 here · 1 away</span></div><section className="meeting-question"><span>QUESTION 01 / 08</span><h2>How much do you trust the narrator at this point?</h2><button className="text-btn">Next question →</button></section><div className="meeting-stack"><button><CircleHelp/><span>7 saved questions</span></button><button><Sparkles/><span>2 predictions</span></button><button><Vote/><span>1 unresolved poll</span></button></div><div className="poll-options"><button className={poll==='book'?'selected':''} onClick={()=>setPoll('book')}>Book was better</button><button className={poll==='movie'?'selected':''} onClick={()=>setPoll('movie')}>Movie was better</button></div><a className="primary full-button facetime-link" href="facetime://">Join FaceTime</a></Modal>
 </div>
}
