import { useState } from 'react';
import { ArrowLeft, Pencil, Check, Upload, GripVertical } from 'lucide-react';
import { books, goodreadsRead, members, type Book } from '../data/demo';
import { EditorialShelf } from '../components/EditorialShelf';
import { Modal } from '../components/Modal';
export function ProfilePage({person='neha',back,onSearch}:{person?:string;back?:()=>void;onSearch:()=>void}){
 const m=members.find(x=>x.id===person)??members[0]; const mine=person==='neha'; const [signature,setSignature]=useState<Book>(mine?books[0]:books[5]); const [editing,setEditing]=useState(false); const [notice,setNotice]=useState(''); const [imported,setImported]=useState(true);
 const choose=(b:Book)=>{setSignature(b);setEditing(false);setNotice(`${b.title} is now your signature book.`);setTimeout(()=>setNotice(''),2200)};
 return <div className="page profile-page"><header className="simple-head">{back?<button className="icon-btn" onClick={back} aria-label="Back"><ArrowLeft/></button>:<span/>}<button className="icon-btn" onClick={()=>setNotice('Account and privacy settings opened.')} aria-label="Profile options"><span>•••</span></button></header>{notice&&<div className="toast-inline"><Check size={15}/>{notice}</div>}
 <section className="profile-hero"><h1>{m.name}</h1><p>{m.handle}</p><div className="signature-book"><img src={signature.cover}/><div><div className="section-label">SIGNATURE BOOK</div><h2>{signature.title}</h2><p>{signature.author}</p>{mine&&<button className="text-btn" onClick={()=>setEditing(true)}><Pencil size={14}/> Edit</button>}</div></div><div className="profile-stats"><div><b>{mine?37:29}</b><span>Books Read</span></div><div><b>{mine?4:3}</b><span>Clubs</span></div><div><b>{mine?12:8}</b><span>5-star reads</span></div></div></section>
 {mine&&<section className="goodreads-strip"><div><span className="section-label">GOODREADS IMPORT</span><h2>{imported?'Reading history synced':'Bring your books with you'}</h2><p>{imported?'37 read books, ratings, dates, and shelves are available in My Books.':'Upload your Goodreads CSV to populate Books Read and Want to Read.'}</p></div><button className="secondary" onClick={()=>{setImported(true);setNotice('Goodreads CSV import ready.')}}><Upload size={16}/> {imported?'Re-import':'Import CSV'}</button></section>}
 <section className="taste-facts"><article className="taste-card petal"><span>APPARENTLY…</span><h3>You really like unreliable narrators.</h3><p>5 of your highest-rated books share the trait.</p></article><article className="taste-card olive"><span>MOST READ AUTHOR</span><h3>Joan Didion</h3><p>3 books in your reading history.</p></article><article className="taste-card butter"><span>YOUR 5★ SHELF</span><h3>34% thrillers</h3><p>More than any other genre.</p></article></section>
 <div className="shelves-head"><h2>My shelves</h2>{mine&&<button className="text-btn add-books-btn" onClick={onSearch}>+ Add books</button>}</div><EditorialShelf title="All-time Favorites" books={mine?books.slice(0,4):[books[5],books[2],books[6],books[3]]} tone="pink" onSeeAll={onSearch}/><EditorialShelf title="Books Read" books={goodreadsRead.slice(0,5)} tone="butter" onSeeAll={onSearch}/><EditorialShelf title="Thrillers" books={[books[3],books[4],books[1],books[0]]} tone="blue" onSeeAll={onSearch}/><EditorialShelf title="Classics" books={[books[8],books[7],books[9],books[6]]} tone="olive" onSeeAll={onSearch}/>
 <section className="reading-year"><div className="section-row"><div><span className="section-label">YOUR READING YEAR</span><h2>2026</h2></div><span className="reading-year-count">18 books</span></div><div className="year-cover-mosaic">{goodreadsRead.slice(0,8).map((b,i)=><img key={b.id} src={b.cover} style={{transform:`rotate(${[-3,2,-1,3,0,-2,2,-1][i]}deg)`}}/>)}</div><div className="year-observations"><p>You gave exactly <b>one</b> book five stars this year.</p><p>May was apparently your <b>thriller month.</b></p><p>You read <b>2,146 pages</b> this summer.</p></div></section>
 <section className="year-ranking"><div className="section-row"><div><span className="section-label">BOOKS OF THE YEAR</span><h2>2026 ranking</h2></div><button className="text-btn">Edit ranking</button></div>{[books[0],books[4],books[2],books[1]].map((b,i)=><article key={b.id}><GripVertical size={16}/><b>0{i+1}</b><img src={b.cover}/><div><h3>{b.title}</h3><span>{b.author}</span></div></article>)}</section>
 <section className="annual-volume"><div><span className="section-label">PERSONAL ARCHIVE</span><h2>Volume I · 2026</h2><p>Your books, ratings, favorite covers, and the small things you’ll forget by next year.</p><button className="text-btn">Preview your year →</button></div><div className="annual-stack">{books.slice(0,3).map((b,i)=><img key={b.id} src={b.cover} style={{transform:`translateX(${i*24}px) rotate(${i*3-3}deg)`}}/>)}</div></section>
 <Modal open={editing} onClose={()=>setEditing(false)} title="Choose your signature book" className="book-picker-sheet"><p className="modal-lede">Pick the cover that should set the tone for your profile.</p><div className="signature-grid">{books.slice(0,8).map(b=><button key={b.id} className={`signature-option ${signature.id===b.id?'selected':''}`} onClick={()=>choose(b)}><img src={b.cover}/><span>{b.title}</span></button>)}</div><button className="secondary full-button" onClick={()=>{setEditing(false);onSearch()}}>Search another book</button></Modal></div>
}
