import { useMemo, useState } from 'react';
import { ArrowLeft, Share2, LockKeyhole, MapPin, CalendarDays, Sparkles, Check, Search, Quote, MessageCircle, Unlock } from 'lucide-react';
import { books, contextItems, members, thoughts } from '../data/demo';
import { DepthSwitch } from '../components/DepthSwitch';

const characterData=[
 {name:'The narrator',role:'Narrator',desc:'Maxim de Winter’s second wife. New to Manderley and constantly measuring herself against the woman who came before her.',img:'https://images.unsplash.com/photo-1524250502761-1ac6f2e30d43?auto=format&fit=crop&w=700&q=80',tone:'petal'},
 {name:'Maxim de Winter',role:'Husband',desc:'Owner of Manderley. Reserved, older, and difficult for the narrator to read.',img:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=700&q=80',tone:'olive'},
 {name:'Mrs. Danvers',role:'Housekeeper',desc:'Manderley’s formidable housekeeper, fiercely devoted to Rebecca’s memory.',img:'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=700&q=80',tone:'butter'},
 {name:'Rebecca',role:'The first Mrs. de Winter',desc:'Dead before the novel begins, yet present in nearly every room, routine, and comparison.',img:'https://images.unsplash.com/photo-1496440737103-cd596325d314?auto=format&fit=crop&w=700&q=80',tone:'wine'}
];
export function ReadingRoom({back}:{back:()=>void}){const current=books[0]; const [tab,setTab]=useState<'discussion'|'context'|'calendar'|'notes'|'characters'>('discussion'); const [depth,setDepth]=useState<'short'|'medium'|'deep'>('short'); const [noteOpen,setNoteOpen]=useState(false); const [note,setNote]=useState(''); const [saved,setSaved]=useState(false); const [shared,setShared]=useState(false); const [lookup,setLookup]=useState(''); const [lookupOpen,setLookupOpen]=useState(false);
 const lookupResult=useMemo(()=>characterData.find(c=>c.name.toLowerCase().includes(lookup.toLowerCase())),[lookup]); const saveNote=()=>{if(!note.trim()) return; setSaved(true); setTimeout(()=>{setNote('');setNoteOpen(false);setSaved(false)},700)};
 return <div className="page reading-room"><header className="simple-head"><button className="icon-btn" onClick={back} aria-label="Back"><ArrowLeft/></button><button className="icon-btn" aria-label="Share book" onClick={async()=>{try{if(navigator.share) await navigator.share({title:`${current.title} · BOOK CLUB`,text:`I'm reading ${current.title} by ${current.author}`}); else {await navigator.clipboard?.writeText(location.href);setShared(true);setTimeout(()=>setShared(false),1500)}}catch{}}}><Share2/></button></header>{shared&&<div className="toast-inline share-toast">Link copied</div>}
 <section className="reading-hero"><div><div className="reading-status">CURRENT BOOK · SUNDAY READERS</div><h1>REBECCA</h1><p className="reading-author">by <em>Daphne du Maurier</em></p><div className="reading-position"><span>YOU’RE HERE</span><strong>Chapter 12</strong><small>47% complete</small></div><div className="progress"><i style={{width:'47%'}}/></div><div className="reader-utility-row"><button onClick={()=>setLookupOpen(v=>!v)}><Search size={15}/> Who is that?</button><button onClick={()=>setTab('context')}><Sparkles size={15}/> What does that mean?</button></div></div><div className="scrap-photo"><img src="https://images.unsplash.com/photo-1500076656116-558758c991c1?auto=format&fit=crop&w=800&q=80"/><span className="tape"/><em>Manderley, imagined</em></div></section>
 {lookupOpen&&<section className="quick-lookup"><div className="quick-lookup-head"><span>WHO IS THAT?</span><b>No spoilers past Chapter 12.</b></div><div className="lookup-input"><Search size={17}/><input autoFocus value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="Try Mrs. Danvers…"/></div>{lookup&&<div className="lookup-result">{lookupResult?<><img src={lookupResult.img}/><div><span>{lookupResult.role}</span><h3>{lookupResult.name}</h3><p>{lookupResult.desc}</p></div></>:<p>Nothing obvious yet. If the book hasn’t explained it, we won’t either.</p>}</div>}</section>}
 <nav className="book-tabs">{(['discussion','context','calendar','notes','characters'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav>
 {tab==='context'&&<section className="context"><div className="section-row context-heading"><div><h2>Context for Chapter 12.</h2><p>Places, history, author background, and references that help without getting ahead of you.</p></div><span className="beta">SPOILER SAFE</span></div><section className="moodboard"><div className="mood-copy"><span>THE WORLD OF REBECCA</span><h3>Sea air, inherited rooms, and a house built around somebody else’s memory.</h3></div><img className="mood-main" src="https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1000&q=80"/><img className="mood-small" src="https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80"/><div className="mood-map"><MapPin size={18}/><b>Cornwall</b><span>Southwest England</span></div><div className="mood-caption"><span>1938</span><p>Published on the edge of a changing country-estate world.</p></div></section><div className="spoiler-select"><LockKeyhole size={16}/> Spoilers through <b>Chapter 12</b></div><DepthSwitch value={depth} onChange={setDepth}/><div className="context-stack">{contextItems.map((item,i)=><article className="context-article" key={item.title}><div className="context-number">0{i+1}</div><div><div className="section-label">{item.kicker}</div><h3>{item.title}</h3><p>{depth==='short'?item.short:depth==='medium'?item.medium:item.deep}</p></div></article>)}</div></section>}
 {tab==='discussion'&&<section className="discussion"><div className="discussion-kicker">WHAT WE’RE THINKING</div><h2>Through Chapter 12</h2><div className="unlock-banner"><Unlock size={17}/><div><b>You just unlocked 4 things.</b><span>Progress is the spoiler filter — not homework.</span></div></div>{thoughts.map(t=>{const m=members.find(x=>x.id===t.user)!;const locked=t.chapter>12;return <article className={`thought ${locked?'locked':''}`} key={t.id}><header><img src={m.avatar}/><div><b>{m.name}</b><span>CH. {t.chapter} · {t.ago}</span></div></header>{locked?<div className="spoiler-block"><LockKeyhole/> Ahead of you — unlock at Chapter {t.chapter}</div>:<><p>{t.text}</p><footer>{Object.entries(t.reactions).map(([r,n])=><button key={r}>{r} {n}</button>)}<button>Reply · {t.replies}</button><button className="thought-share" onClick={async()=>{if(navigator.share) await navigator.share({title:`${m.name} · Chapter ${t.chapter}`,text:t.text,url:location.href}).catch(()=>{});else await navigator.clipboard?.writeText(location.href)}}><Share2 size={13}/> Share</button></footer></>}</article>})}</section>}
 {tab==='calendar'&&<section className="reading-calendar"><div className="section-row"><div><div className="section-label">PROPOSED READING PLAN</div><h2>Sep 22 — Oct 20</h2></div><button className="text-btn">Adjust pace</button></div><p className="calendar-note">Suggested, not homework. Read however you want; this just keeps the club oriented.</p>{[['SEP 22','START','Ch. 1'],['SEP 29','CHECKPOINT','Through Ch. 7'],['OCT 06','CHECKPOINT','Through Ch. 14'],['OCT 13','CHECKPOINT','Through Ch. 20'],['OCT 20','FINISH','Finish the book']].map((r,i)=><article className="timeline-row" key={r[0]}><div className={`timeline-dot ${i===2?'current':''}`}/><time>{r[0]}</time><div><span>{r[1]}</span><h3>{r[2]}</h3>{i===2&&<div className="timeline-members">{members.map(m=><span key={m.id}>{m.name[0]} {m.chapter}</span>)}</div>}</div>{i===4&&<CalendarDays size={19}/>}</article>)}</section>}
 {tab==='notes'&&<section className="empty-editorial"><h2>YOUR MARGINS ARE QUIET.</h2><p>Save a quote, prediction, or private note while you read.</p>{!noteOpen?<button className="primary" onClick={()=>setNoteOpen(true)}>Add a note</button>:<div className="inline-note"><textarea autoFocus value={note} onChange={e=>setNote(e.target.value)} placeholder="Write something you want to remember…"/><div><button className="text-btn" onClick={()=>{setNoteOpen(false);setNote('')}}>Cancel</button><button className="primary" disabled={!note.trim()} onClick={saveNote}>{saved?<><Check size={16}/> Saved</>:'Save note'}</button></div></div>}<div className="notes-types"><article><Quote/><b>Quotes</b><span>Save the line, not a screenshot.</span></article><article><MessageCircle/><b>Private notes</b><span>Only you can see these.</span></article><article><Sparkles/><b>Predictions</b><span>Lock them now. Check the receipts later.</span></article></div></section>}
 {tab==='characters'&&<section className="characters"><div className="section-row"><h2>Character map</h2><span className="spoiler-safe"><LockKeyhole size={14}/> through Ch. 12</span></div><div className="character-grid">{characterData.map(c=><article key={c.name} className={`character-card ${c.tone}`}><img src={c.img} alt=""/><div><span>{c.role}</span><h3>{c.name}</h3><p>{c.desc}</p></div></article>)}</div><div className="relationship-strip"><Sparkles/><div><b>What matters right now</b><p>The narrator is trying to understand a household whose routines, loyalties, and standards were built around Rebecca.</p></div></div></section>}
 </div>
}
