import { useEffect, useState } from 'react';
import { Search, X, Check, Plus, ArrowLeft, Clock3, Users, Film } from 'lucide-react';
import { books as demoBooks, type Book } from '../data/demo';
import { searchBooks, type BookSearchResult } from '../lib/books';
export function SearchPage(){const [q,setQ]=useState(''); const [results,setResults]=useState<BookSearchResult[]>([]); const [loading,setLoading]=useState(false); const [added,setAdded]=useState<Set<string>>(new Set()); const [detail,setDetail]=useState<any|null>(null);
 useEffect(()=>{const t=setTimeout(async()=>{if(q.trim().length<2){setResults([]);return} setLoading(true);setResults(await searchBooks(q));setLoading(false)},300); return()=>clearTimeout(t)},[q]); const shown=q?results:demoBooks.map(b=>({key:b.id,title:b.title,author:b.author,cover:b.cover,year:b.year,pages:b.pages,genres:b.genres})); const add=(b:any)=>setAdded(prev=>new Set(prev).add(b.key||b.id));
 if(detail) return <div className="page book-preview-page"><header className="simple-head"><button className="icon-btn" onClick={()=>setDetail(null)}><ArrowLeft/></button><span className="section-label">BOOK PREVIEW</span></header><section className="book-preview-hero"><img src={detail.cover}/><div><h1>{detail.title}</h1><p>by <em>{detail.author}</em></p><div className="metadata-line"><span>{detail.pages||449} pages</span><span>{detail.year||1938}</span><span>{detail.genres?.[0]||'Literary'}</span></div></div></section><p className="book-premise">{(demoBooks.find((b:Book)=>b.title===detail.title)?.description)||'A spoiler-free preview of the book, its tone, and what your club should know before deciding.'}</p><section className="club-fit"><h2>For Sunday Readers</h2><div><Users/><span><b>2 members</b> already want to read it</span></div><div><Check/><span><b>Alex</b> has already read it · ★★★★½</span></div><div><Clock3/><span>About <b>{demoBooks.find(b=>b.title===detail.title)?.readingHours||9} hours</b> of reading</span></div><div><Film/><span>No adaptation conflicts with your meeting plan</span></div></section><button className="primary full-button" onClick={()=>{add(detail);setDetail(null)}}>Nominate for next book</button></div>;
 return <div className="page search-page"><header className="title-head"><div><div className="section-label">FIND YOUR NEXT COVER</div><h1>Search books</h1></div></header><p className="lede search-lede">Search a title, author, or ISBN. Open a book first to see whether it fits your club.</p><div className="search-box"><Search/><input value={q} onChange={e=>setQ(e.target.value)} autoFocus placeholder="Title, author, ISBN…"/>{q&&<button onClick={()=>setQ('')} aria-label="Clear search"><X/></button>}</div>{loading&&<div className="book-grid">{Array.from({length:8}).map((_,i)=><div className="book-skeleton" key={i}/>)}</div>}<div className="book-grid">{!loading&&shown.map((b:any)=><button className={`search-book ${added.has(b.key)?'added':''}`} key={b.key} onClick={()=>setDetail(b)}><div className="search-cover-wrap"><img src={b.cover}/><span className="add-badge">{added.has(b.key)?<Check size={16}/>:<Plus size={16}/>}</span></div><strong>{b.title}</strong><span>{b.author}</span><small>{added.has(b.key)?'In My Books':(b.year||'')}</small></button>)}</div></div>
}
