const rateBuckets=new Map();
const enc=new TextEncoder(),dec=new TextDecoder();
function cors(request,env){const origin=request.headers.get('origin')||'';const allowed=env.APP_ORIGIN&&origin===env.APP_ORIGIN?origin:(env.APP_ORIGIN?'':origin||'*');return{'access-control-allow-origin':allowed||env.APP_ORIGIN||'*','vary':'Origin','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization','access-control-max-age':'86400'}}
function json(data,status=200,request,env,extra={}){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json',...cors(request,env),...extra}})}
async function timedFetch(url,init={},ms=12000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{return await fetch(url,{...init,signal:c.signal})}finally{clearTimeout(t)}}
async function fetchJson(url,init,ms){const r=await timedFetch(url,init,ms);const j=await r.json().catch(()=>null);if(!r.ok)throw new Error(j?.error?.message||j?.error_description||j?.message||`${r.status} ${url}`);return j}
function outputText(r){if(typeof r?.output_text==='string')return r.output_text;for(const item of r?.output||[])for(const c of item?.content||[])if(c?.type==='output_text'&&c?.text)return c.text;return''}
function safeJson(text){try{return JSON.parse(text)}catch{}const m=String(text||'').match(/[\[{][\s\S]*[\]}]/);if(m)try{return JSON.parse(m[0])}catch{}return null}
function b64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64url(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function hmac(secret,text){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,enc.encode(text))))}
async function stateFor(env,userId){const payload=b64url(enc.encode(JSON.stringify({u:userId,t:Date.now()})));return `${payload}.${await hmac(env.CALENDAR_STATE_SECRET||env.GOOGLE_CLIENT_SECRET||'missing',payload)}`}
async function verifyState(env,state){const [payload,sig]=String(state||'').split('.');if(!payload||!sig)return null;const expected=await hmac(env.CALENDAR_STATE_SECRET||env.GOOGLE_CLIENT_SECRET||'missing',payload);if(expected!==sig)return null;try{const d=JSON.parse(dec.decode(unb64url(payload)));if(!d.u||Date.now()-Number(d.t)>10*60*1000)return null;return d.u}catch{return null}}
async function aesKey(secret){const digest=await crypto.subtle.digest('SHA-256',enc.encode(secret));return crypto.subtle.importKey('raw',digest,'AES-GCM',false,['encrypt','decrypt'])}
async function encrypt(env,value){if(!env.TOKEN_ENCRYPTION_KEY)throw new Error('TOKEN_ENCRYPTION_KEY is not configured');const iv=crypto.getRandomValues(new Uint8Array(12)),key=await aesKey(env.TOKEN_ENCRYPTION_KEY);const cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,enc.encode(JSON.stringify(value))));const all=new Uint8Array(iv.length+cipher.length);all.set(iv);all.set(cipher,iv.length);return b64url(all)}
async function decrypt(env,value){const all=unb64url(value),iv=all.slice(0,12),cipher=all.slice(12),key=await aesKey(env.TOKEN_ENCRYPTION_KEY);return JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher)))}
function supaHeaders(env,bearer){return{apikey:env.SUPABASE_ANON_KEY||'',authorization:bearer||`Bearer ${env.SUPABASE_ANON_KEY||''}`,'content-type':'application/json'}}
function adminHeaders(env){return{apikey:env.SUPABASE_SERVICE_ROLE_KEY||'',authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY||''}`,'content-type':'application/json'}}
async function authedUser(request,env){if(!env.SUPABASE_URL||!env.SUPABASE_ANON_KEY)throw new Error('Supabase Worker configuration is incomplete');const auth=request.headers.get('authorization');if(!auth?.startsWith('Bearer '))return null;try{return await fetchJson(`${env.SUPABASE_URL}/auth/v1/user`,{headers:supaHeaders(env,auth)},7000)}catch{return null}}
async function userRpc(env,auth,name,body){return fetchJson(`${env.SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:supaHeaders(env,auth),body:JSON.stringify(body)},10000)}
async function adminSelect(env,table,query){return fetchJson(`${env.SUPABASE_URL}/rest/v1/${table}?${query}`,{headers:adminHeaders(env)},10000)}
async function adminUpsert(env,table,body,onConflict){return fetchJson(`${env.SUPABASE_URL}/rest/v1/${table}${onConflict?`?on_conflict=${encodeURIComponent(onConflict)}`:''}`,{method:'POST',headers:{...adminHeaders(env),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(body)},10000)}
async function adminDelete(env,table,query){const r=await timedFetch(`${env.SUPABASE_URL}/rest/v1/${table}?${query}`,{method:'DELETE',headers:adminHeaders(env)},10000);if(!r.ok)throw new Error(`Supabase delete failed (${r.status})`)}
function rateLimit(key,limit=20,windowMs=60000){const now=Date.now(),old=rateBuckets.get(key);if(!old||now-old.start>windowMs){rateBuckets.set(key,{start:now,count:1});return true}old.count++;return old.count<=limit}
async function sourceContext(title,author){const out={description:'',wikipedia:'',subjects:[],sources:[]};try{const ol=await fetchJson(`https://openlibrary.org/search.json?title=${encodeURIComponent(title)}&author=${encodeURIComponent(author||'')}&limit=1&fields=key,title,author_name,subject`,{},8000);const d=ol?.docs?.[0];out.subjects=(d?.subject||[]).slice(0,18);if(d?.key?.startsWith('/works/')){const w=await fetchJson(`https://openlibrary.org${d.key}.json`,{},8000);out.description=typeof w?.description==='string'?w.description:(w?.description?.value||'');out.subjects=[...new Set([...(out.subjects||[]),...(w?.subjects||[])])].slice(0,24);out.sources.push({name:'Open Library',url:`https://openlibrary.org${d.key}`})}}catch{}try{const s=await fetchJson(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(title+' '+author)}&utf8=1&format=json&origin=*`,{},8000);const hit=s?.query?.search?.[0];if(hit){const p=await fetchJson(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(hit.title)}`,{},8000);out.wikipedia=p?.extract||'';if(p?.content_urls?.desktop?.page)out.sources.push({name:'Wikipedia',url:p.content_urls.desktop.page})}}catch{}return out}
async function openLibraryCandidate(title,author){try{const j=await fetchJson(`https://openlibrary.org/search.json?title=${encodeURIComponent(title)}&author=${encodeURIComponent(author||'')}&limit=1&fields=key,title,author_name,cover_i,first_publish_year,number_of_pages_median,isbn`,{},8000);const d=j?.docs?.[0];if(!d)return null;return{title:d.title||title,author:d.author_name?.[0]||author||'Unknown author',year:d.first_publish_year||undefined,pages:d.number_of_pages_median||undefined,isbn:d.isbn?.[0]||undefined,cover:d.cover_i?`https://covers.openlibrary.org/b/id/${d.cover_i}-L.jpg`:undefined}}catch{return null}}
async function openAi(env,prompt){if(!env.OPENAI_API_KEY)throw new Error('AI synthesis is not configured');const r=await fetchJson('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify({model:env.OPENAI_MODEL||'gpt-5.6',input:prompt,store:false})},30000);return safeJson(outputText(r))}
async function openAiVision(env,prompt,imageDataUrl){if(!env.OPENAI_API_KEY)throw new Error('Passage scanning is not configured');const r=await fetchJson('https://api.openai.com/v1/responses',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${env.OPENAI_API_KEY}`},body:JSON.stringify({model:env.OPENAI_VISION_MODEL||env.OPENAI_MODEL||'gpt-5.6',input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:imageDataUrl,detail:'high'}]}],store:false})},45000);return safeJson(outputText(r))}
function calendarConfigured(env){return Boolean(env.SUPABASE_URL&&env.SUPABASE_ANON_KEY&&env.SUPABASE_SERVICE_ROLE_KEY&&env.GOOGLE_CLIENT_ID&&env.GOOGLE_CLIENT_SECRET&&env.GOOGLE_REDIRECT_URI&&env.APP_ORIGIN&&env.TOKEN_ENCRYPTION_KEY)}
async function calendarConnection(env,userId){const r=await adminSelect(env,'calendar_connections',`user_id=eq.${encodeURIComponent(userId)}&select=*`);return r?.[0]||null}
async function refreshedTokens(env,conn){let tokens=await decrypt(env,conn.encrypted_tokens);if(tokens.expires_at&&Number(tokens.expires_at)>Date.now()+60000)return tokens;if(!tokens.refresh_token)throw new Error('Google Calendar needs to be reconnected');const p=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,grant_type:'refresh_token',refresh_token:tokens.refresh_token});const next=await fetchJson('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:p},12000);tokens={...tokens,...next,expires_at:Date.now()+Number(next.expires_in||3600)*1000};await adminUpsert(env,'calendar_connections',{user_id:conn.user_id,encrypted_tokens:await encrypt(env,tokens),email:conn.email,expires_at:new Date(tokens.expires_at).toISOString(),scope:tokens.scope||conn.scope,updated_at:new Date().toISOString()},'user_id');return tokens}
async function syncCalendarMeeting(env,userId,meetingId){const conn=await calendarConnection(env,userId);if(!conn)throw new Error('Connect Google Calendar first');const meetings=await adminSelect(env,'meetings',`id=eq.${encodeURIComponent(meetingId)}&select=id,club_id,club_book_id,starts_at,meeting_type,meeting_url,status`);const m=meetings?.[0];if(!m)throw new Error('Meeting not found');const membership=await adminSelect(env,'club_members',`club_id=eq.${m.club_id}&user_id=eq.${userId}&select=role`);if(!membership?.length)throw new Error('Not a club member');const clubs=await adminSelect(env,'clubs',`id=eq.${m.club_id}&select=name`);let bookTitle='';if(m.club_book_id){const cb=await adminSelect(env,'club_books',`id=eq.${m.club_book_id}&select=book_id`);if(cb?.[0]?.book_id){const bs=await adminSelect(env,'books',`id=eq.${cb[0].book_id}&select=title,author`);if(bs?.[0])bookTitle=` · ${bs[0].title}`}}const tokens=await refreshedTokens(env,conn);const start=new Date(m.starts_at),end=new Date(start.getTime()+90*60000);const event={summary:`BOOK CLUB · ${clubs?.[0]?.name||'Meeting'}${bookTitle}`,description:'Book club meeting scheduled in BOOK CLUB.',start:{dateTime:start.toISOString()},end:{dateTime:end.toISOString()},location:m.meeting_url||undefined};const links=await adminSelect(env,'calendar_event_links',`user_id=eq.${userId}&meeting_id=eq.${meetingId}&select=*`);const old=links?.[0];const endpoint=old?`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(old.google_event_id)}`:'https://www.googleapis.com/calendar/v3/calendars/primary/events';const saved=await fetchJson(endpoint,{method:old?'PUT':'POST',headers:{'content-type':'application/json',authorization:`Bearer ${tokens.access_token}`},body:JSON.stringify(event)},12000);await adminUpsert(env,'calendar_event_links',{user_id:userId,meeting_id:meetingId,google_event_id:saved.id,html_link:saved.htmlLink||null,last_synced_at:new Date().toISOString()},'user_id,meeting_id');return{ok:true,htmlLink:saved.htmlLink}}

export default{async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{headers:cors(request,env)});
  if(url.pathname==='/api/book-discovery'){
    const cacheHeaders={'cache-control':'public, max-age=1800, s-maxage=21600'};
    const nyt=[];
    if(env.NYT_BOOKS_API_KEY){
      for(const list of ['hardcover-fiction','hardcover-nonfiction']){
        try{const d=await fetchJson(`https://api.nytimes.com/svc/books/v3/lists/current/${list}.json?api-key=${env.NYT_BOOKS_API_KEY}`,{},9000);for(const b of (d?.results?.books||[]).slice(0,6))nyt.push({key:`nyt:${b.primary_isbn13||b.primary_isbn10||b.rank}`,source:'nyt',title:b.title,author:b.author,cover:b.book_image||'',isbn:b.primary_isbn13||b.primary_isbn10,rank:b.rank,weeksOnList:b.weeks_on_list,listName:d?.results?.display_name||'',storeUrl:b.amazon_product_url||''})}catch{}
      }
    }
    const apple=[];
    const terms=['literary fiction','thriller','memoir'];
    for(const term of terms){
      try{const d=await fetchJson(`https://itunes.apple.com/search?term=${encodeURIComponent(term)}&country=US&media=ebook&entity=ebook&limit=8&explicit=No`,{},9000);for(const b of (d?.results||[])){const title=b.trackName||b.collectionName;if(!title||apple.some(x=>x.title.toLowerCase()===String(title).toLowerCase()))continue;apple.push({key:`apple:${b.trackId||b.collectionId}`,source:'apple',title,author:b.artistName||'Unknown author',cover:String(b.artworkUrl100||'').replace('100x100','600x600'),year:Number(String(b.releaseDate||'').slice(0,4))||undefined,isbn:b.isbn13||undefined,subjects:b.genres||[],storeUrl:b.trackViewUrl||b.collectionViewUrl||''});if(apple.length>=12)break}}catch{}if(apple.length>=12)break
    }
    return json({nyt:nyt.slice(0,10),apple:apple.slice(0,10),nytConfigured:Boolean(env.NYT_BOOKS_API_KEY)},200,request,env,cacheHeaders);
  }
  if(url.pathname==='/api/health')return json({ok:true,services:{openLibrary:true,wikipedia:true,ai:Boolean(env.OPENAI_API_KEY),calendarConfigured:calendarConfigured(env),tmdb:Boolean(env.TMDB_BEARER_TOKEN),youtube:Boolean(env.YOUTUBE_API_KEY),supabase:Boolean(env.SUPABASE_URL&&env.SUPABASE_ANON_KEY)}},200,request,env);
  if(url.pathname==='/api/transcribe-passage'&&request.method==='POST'){
    const user=await authedUser(request,env);if(!user)return json({error:'Sign in required'},401,request,env);
    if(!env.OPENAI_API_KEY)return json({error:'Passage scanning is not configured yet.'},503,request,env);
    if(!rateLimit(`passage:${user.id}`,12,60000))return json({error:'Too many scans at once. Try again in a minute.'},429,request,env);
    let body;try{body=await request.json()}catch{return json({error:'invalid json'},400,request,env)}
    const imageDataUrl=String(body?.imageDataUrl||'');
    if(!/^data:image\/(jpeg|jpg|png|webp);base64,/i.test(imageDataUrl))return json({error:'A readable photo is required.'},400,request,env);
    if(imageDataUrl.length>6500000)return json({error:'That photo is too large. Take it again a little closer.'},413,request,env);
    const title=String(body?.title||'').slice(0,240),author=String(body?.author||'').slice(0,180),currentChapter=Number(body?.currentChapter)||0;
    try{
      const parsed=await openAiVision(env,`You are a high-accuracy OCR engine for a private book club. Read the photographed printed-book passage exactly as it appears. Do not summarize, paraphrase, modernize, fix grammar, or invent missing words. Preserve paragraph breaks and punctuation. Ignore running headers, decorative title text, footers, and the printed page number as body text, but separately identify a visible page number. If a chapter number is visibly printed, return it; otherwise return null. Book metadata is only a hint for orientation: ${title||'unknown title'} by ${author||'unknown author'}. Reader's current chapter is ${currentChapter||'unknown'}; do not assume that is the photographed chapter. Confidence must reflect literal transcription confidence, not prose quality. Set needsReview true if any meaningful words are obscured, blurred, cropped, heavily curved, or uncertain. If uncertain about a word, do not silently guess; set needsReview true. Return ONLY JSON in this shape: {"text":"exact transcription","confidence":0.0,"needsReview":false,"pageNumber":null,"chapterNumber":null}.`,imageDataUrl);
      const text=String(parsed?.text||'').trim();if(!text)return json({error:'No readable passage found. Try a closer, brighter photo.'},422,request,env);
      const confidence=Math.max(0,Math.min(1,Number(parsed?.confidence)||0));
      return json({text,confidence,needsReview:Boolean(parsed?.needsReview)||confidence<0.9,pageNumber:Number(parsed?.pageNumber)||null,chapterNumber:Number(parsed?.chapterNumber)||null},200,request,env);
    }catch(e){return json({error:e?.message?.includes('timed')?'Passage scan timed out. Try a closer photo.':'Could not read that passage. Try another photo.'},502,request,env)}
  }

  if(url.pathname==='/api/enrich'){const title=url.searchParams.get('title')||'',author=url.searchParams.get('author')||'';if(!title)return json({error:'title required'},400,request,env);const source=await sourceContext(title,author);const out={title,author,wikipedia:source.wikipedia?{extract:source.wikipedia}:null,adaptations:[],videos:[],sources:source.sources};if(env.TMDB_BEARER_TOKEN)try{const t=await fetchJson(`https://api.themoviedb.org/3/search/multi?query=${encodeURIComponent(title)}&include_adult=false`,{headers:{Authorization:`Bearer ${env.TMDB_BEARER_TOKEN}`}},8000);out.adaptations=(t.results||[]).slice(0,5).map(x=>({id:x.id,type:x.media_type,title:x.title||x.name,year:(x.release_date||x.first_air_date||'').slice(0,4),poster:x.poster_path?`https://image.tmdb.org/t/p/w500${x.poster_path}`:null}))}catch{}if(env.YOUTUBE_API_KEY)try{const y=await fetchJson(`https://www.googleapis.com/youtube/v3/search?part=snippet&type=video&maxResults=5&q=${encodeURIComponent(title+' '+author+' interview')}&key=${env.YOUTUBE_API_KEY}`,{},8000);out.videos=(y.items||[]).map(v=>({id:v.id.videoId,title:v.snippet.title,channel:v.snippet.channelTitle}))}catch{}return json(out,200,request,env)}
  if(url.pathname==='/api/reader-context'&&request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'invalid json'},400,request,env)}const title=String(body?.title||'').trim(),author=String(body?.author||'').trim();if(!title)return json({error:'title required'},400,request,env);const source=await sourceContext(title,author),sources=source.sources||[];if(!env.OPENAI_API_KEY){const subjects=(source.subjects||[]).slice(0,6).map(x=>String(x).replace(/[_-]+/g,' '));return json({items:subjects.length?[{kind:'themes',title:'Catalog context',summary_short:`Cataloged themes include ${subjects.join(', ')}.`,summary_medium:`Catalog metadata for ${title} points to ${subjects.join(', ')}.`,summary_deep:'More context will appear when BOOK CLUB can verify it against reliable sources.',spoiler_chapter:null,context_sources:sources.map(s=>({source_name:s.name,source_url:s.url,source_type:'reference'}))}]:[],ai:false},200,request,env)}const evidence=[source.description,source.wikipedia].filter(Boolean).join('\n\n').slice(0,9000);try{const parsed=await openAi(env,`Create a spoiler-safe Reader's Companion for ${title} by ${author}. Reader progress: chapter ${body?.chapter||0}. Use ONLY supplied evidence and bibliographic metadata. Never invent characters, relationships, plot events, or chapter claims. Prefer author background, history, setting, terminology, themes and places. Every item must explicitly connect the context to why a reader of this book would care; no trivia dumps. Plain, observant language for friends. If the evidence cannot support something confidently, omit it. Evidence:\n${evidence||'No prose evidence.'}\nSubjects: ${(source.subjects||[]).slice(0,24).join(', ')}\nReturn ONLY JSON {"items":[{"kind":"author|setting|history|theme|term|character","title":"...","summary_short":"1-2 sentences","summary_medium":"3-5 sentences","summary_deep":"5-8 sentences"}]}, 3-5 items.`);const items=(parsed?.items||[]).slice(0,5).map((x,i)=>({...x,id:`worker-${i}`,spoiler_chapter:null,context_sources:sources.map(s=>({source_name:s.name,source_url:s.url,source_type:'reference'}))}));return json({items,ai:true},200,request,env)}catch{return json({error:'Reader context unavailable'},502,request,env)}}
  if(url.pathname==='/api/book-decision'&&request.method==='POST'){let body;try{body=await request.json()}catch{return json({error:'invalid json'},400,request,env)}const title=String(body?.title||'').trim(),author=String(body?.author||'').trim();if(!title)return json({error:'title required'},400,request,env);const source=await sourceContext(title,author);if(!env.OPENAI_API_KEY)return json({error:'AI synthesis is not configured',sourceBacked:false},503,request,env);if(!rateLimit(`decision:${request.headers.get('cf-connecting-ip')||'ip'}`,30))return json({error:'Try again in a minute.'},429,request,env);try{const parsed=await openAi(env,`Write a spoiler-free book-club decision guide for friends. Book: ${title}; Author: ${author}; Year: ${body?.year||'unknown'}; Pages: ${body?.pages||'unknown'}; Subjects: ${[...(body?.subjects||[]),...(source.subjects||[])].slice(0,24).join(', ')}. Source context: ${String(body?.description||source.description||source.wikipedia||'').slice(0,8000)}. Rewrite, never quote closely, never invent plot facts. Return ONLY JSON {"whatItsAbout":"2-3 plain-English sentences","whyItWorks":"1-2 sentences","conversation":["3 specific spoiler-free discussion lanes"],"vibe":["3-5 short tags"],"headsUp":"style/pacing/commitment expectation"}.`);if(!parsed)return json({error:'Could not parse synthesis'},502,request,env);return json({...parsed,sourceBacked:true,sources:source.sources},200,request,env)}catch{return json({error:'Synthesis unavailable'},502,request,env)}}
  if(url.pathname==='/api/recommendations'&&request.method==='POST'){const user=await authedUser(request,env);if(!user)return json({error:'Sign in required'},401,request,env);if(!rateLimit(`rec:${user.id}`,10,60000))return json({error:'Try recommendations again in a minute.'},429,request,env);let body;try{body=await request.json()}catch{return json({error:'invalid json'},400,request,env)}const clubId=String(body?.clubId||'');if(!clubId)return json({error:'clubId required'},400,request,env);if(!env.OPENAI_API_KEY)return json({error:'AI recommendations are not configured.'},503,request,env);try{const profile=await userRpc(env,request.headers.get('authorization'),'get_club_taste_profile',{target_club_id:clubId});const parsed=await openAi(env,`Recommend 6 book-club books for a private group of friends. Use this aggregated taste/history JSON: ${JSON.stringify(profile).slice(0,12000)}. Do not repeat books already in ideas or clubHistory. Respect avoidances as real negative constraints unless every option would otherwise fail; use moods as current preference signals. Balance fit with variety; avoid all six being the same genre. Give a concise human reason grounded in supplied taste patterns, e.g. shared favorites, prior ratings, manageable length, nobody having read it, or a current mood. Never use a compatibility percentage or generic AI language. Return ONLY JSON {"suggestions":[{"title":"","author":"","reason":"1-2 sentences","confidence":"high|medium"}]}.`);const raw=(parsed?.suggestions||[]).slice(0,8),suggestions=[];for(const s of raw){const meta=await openLibraryCandidate(s.title,s.author);if(meta)suggestions.push({...meta,reason:String(s.reason||''),confidence:s.confidence||'medium'});if(suggestions.length>=6)break}return json({suggestions},200,request,env)}catch(e){return json({error:e?.message||'Recommendations unavailable'},502,request,env)}}
  if(url.pathname==='/api/calendar/start'&&request.method==='POST'){const user=await authedUser(request,env);if(!user)return json({error:'Sign in required'},401,request,env);if(!calendarConfigured(env))return json({error:'Google Calendar is not configured yet.'},503,request,env);const state=await stateFor(env,user.id);const q=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,redirect_uri:env.GOOGLE_REDIRECT_URI,response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:'openid email https://www.googleapis.com/auth/calendar.events',state});return json({url:`https://accounts.google.com/o/oauth2/v2/auth?${q}`},200,request,env)}
  if(url.pathname==='/api/calendar/callback'){if(!calendarConfigured(env))return new Response('Calendar is not configured',{status:503});const userId=await verifyState(env,url.searchParams.get('state'));const code=url.searchParams.get('code');if(!userId||!code)return new Response('Invalid or expired calendar connection request',{status:400});try{const p=new URLSearchParams({client_id:env.GOOGLE_CLIENT_ID,client_secret:env.GOOGLE_CLIENT_SECRET,redirect_uri:env.GOOGLE_REDIRECT_URI,grant_type:'authorization_code',code});const tokens=await fetchJson('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:p},12000);tokens.expires_at=Date.now()+Number(tokens.expires_in||3600)*1000;let email='';try{const info=await fetchJson('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:`Bearer ${tokens.access_token}`}},8000);email=info.email||''}catch{}await adminUpsert(env,'calendar_connections',{user_id:userId,encrypted_tokens:await encrypt(env,tokens),email,expires_at:new Date(tokens.expires_at).toISOString(),scope:tokens.scope||'',updated_at:new Date().toISOString()},'user_id');return Response.redirect(`${env.APP_ORIGIN}/me/settings?calendar=connected`,302)}catch{return Response.redirect(`${env.APP_ORIGIN}/me/settings?calendar=error`,302)}}
  if(url.pathname.startsWith('/api/calendar/')){const user=await authedUser(request,env);if(!user)return json({error:'Sign in required'},401,request,env);if(!calendarConfigured(env))return json({configured:false,connected:false,error:'Google Calendar is not configured yet.'},url.pathname.endsWith('/status')?200:503,request,env);if(url.pathname==='/api/calendar/status'){const conn=await calendarConnection(env,user.id);return json({configured:true,connected:Boolean(conn),email:conn?.email||undefined,lastSyncedAt:conn?.updated_at||undefined},200,request,env)}if(url.pathname==='/api/calendar/disconnect'&&request.method==='POST'){await adminDelete(env,'calendar_event_links',`user_id=eq.${user.id}`);await adminDelete(env,'calendar_connections',`user_id=eq.${user.id}`);return json({ok:true},200,request,env)}let body;try{body=await request.json()}catch{return json({error:'invalid json'},400,request,env)}const meetingId=String(body?.meetingId||'');if(!meetingId)return json({error:'meetingId required'},400,request,env);if(url.pathname==='/api/calendar/sync'&&request.method==='POST')try{return json(await syncCalendarMeeting(env,user.id,meetingId),200,request,env)}catch(e){return json({error:e?.message||'Calendar sync failed'},502,request,env)}if(url.pathname==='/api/calendar/remove-event'&&request.method==='POST'){try{const conn=await calendarConnection(env,user.id),links=await adminSelect(env,'calendar_event_links',`user_id=eq.${user.id}&meeting_id=eq.${meetingId}&select=*`),link=links?.[0];if(conn&&link){const tokens=await refreshedTokens(env,conn);const r=await timedFetch(`https://www.googleapis.com/calendar/v3/calendars/primary/events/${encodeURIComponent(link.google_event_id)}`,{method:'DELETE',headers:{authorization:`Bearer ${tokens.access_token}`}},12000);if(!r.ok&&r.status!==404)throw new Error('Could not remove Google Calendar event')}await adminDelete(env,'calendar_event_links',`user_id=eq.${user.id}&meeting_id=eq.${meetingId}`);return json({ok:true},200,request,env)}catch(e){return json({error:e?.message||'Could not remove event'},502,request,env)}}}
  return json({error:'not found'},404,request,env)
}};
