import { useState } from 'react';
import { Copy, Bell, UserPlus, Check } from 'lucide-react';
import { BottomNav, type Tab } from './components/BottomNav';
import { HomePage } from './pages/HomePage'; import { ClubsPage } from './pages/ClubsPage'; import { SearchPage } from './pages/SearchPage'; import { ProfilePage } from './pages/ProfilePage'; import { ReadingRoom } from './pages/ReadingRoom'; import { ThoughtComposer } from './pages/ThoughtComposer'; import { Modal } from './components/Modal'; import { books, clubs as demoClubs, type Club } from './data/demo';
export default function App(){
 const [tab,setTab]=useState<Tab>('home'); const [clubList,setClubList]=useState<Club[]>(demoClubs); const [activeClub,setActiveClub]=useState<Club>(demoClubs[0]); const [reading,setReading]=useState(false); const [friend,setFriend]=useState<string|null>(null); const [composer,setComposer]=useState(false); const [invite,setInvite]=useState(false); const [notifications,setNotifications]=useState(false); const [copied,setCopied]=useState(false); const [vote,setVote]=useState(false); const [voteChoice,setVoteChoice]=useState<string|null>(null);
 const openOwnProfile=()=>{setFriend(null);setTab('profile')}; const copyInvite=async()=>{try{await navigator.clipboard.writeText(`https://bookclub.example/join/${activeClub.inviteCode}`);setCopied(true);setTimeout(()=>setCopied(false),1600)}catch{setCopied(true)}};
 if(reading) return <main className="app-shell"><ReadingRoom back={()=>setReading(false)}/></main>; if(friend) return <main className="app-shell"><ProfilePage person={friend} back={()=>setFriend(null)} onSearch={()=>{setFriend(null);setTab('search')}}/></main>;
 return <main className="app-shell"><div className="content-wrap">{tab==='home'&&<HomePage club={activeClub} openReading={()=>setReading(true)} openFriend={setFriend} openThought={()=>setComposer(true)} onInvite={()=>setInvite(true)} onNotifications={()=>setNotifications(true)} onProfile={openOwnProfile} onSwitchClub={()=>setTab('clubs')} onVote={()=>setVote(true)} onSearch={()=>setTab('search')}/>} {tab==='clubs'&&<ClubsPage clubs={clubList} activeClub={activeClub} onSelect={c=>{setActiveClub(c);setTab('home')}} onCreate={c=>{setClubList(prev=>[...prev,c]);setActiveClub(c);setTab('home')}}/>}{tab==='search'&&<SearchPage/>}{tab==='profile'&&<ProfilePage onSearch={()=>setTab('search')}/>}</div><BottomNav tab={tab} setTab={setTab}/><ThoughtComposer open={composer} onClose={()=>setComposer(false)}/>
 <Modal open={invite} onClose={()=>setInvite(false)} title="Invite your people"><p className="modal-lede">This link is private. Anyone with it can request to join {activeClub.name}.</p><div className="invite-link"><span>bookclub.app/join/{activeClub.inviteCode}</span><button className="icon-btn" onClick={copyInvite} aria-label="Copy invite">{copied?<Check/>:<Copy/>}</button></div><button className="primary full-button" onClick={async()=>{if(navigator.share){await navigator.share({title:activeClub.name,text:'Join our book club',url:`https://bookclub.example/join/${activeClub.inviteCode}`}).catch(()=>{})}else{copyInvite()}}}><UserPlus size={17}/> Share invite</button><p className="fine-print">The club never appears in public search or discovery.</p></Modal>
 <Modal open={notifications} onClose={()=>setNotifications(false)} title="Notifications"><div className="notification-list"><button onClick={()=>{setNotifications(false);setReading(true)}}><span className="notification-icon petal"><Bell size={16}/></span><div><b>Maya replied to your thought</b><span>{books.find(b=>b.id===activeClub.bookId)?.title} · Chapter 9 · 10m</span></div></button><button onClick={()=>{setNotifications(false);setVote(true)}}><span className="notification-icon butter">✦</span><div><b>Voting closes tomorrow</b><span>Classics Club · 2h</span></div></button><button onClick={()=>{setNotifications(false);setReading(true)}}><span className="notification-icon olive">12</span><div><b>2 thoughts unlocked</b><span>You reached Chapter 12</span></div></button></div></Modal>
 <Modal open={vote} onClose={()=>setVote(false)} title="What should we read next?"><p className="modal-lede">Vote privately. Results are hidden until you submit.</p><div className="vote-grid">{[books[1],books[4],books[5],books[6]].map(b=><button key={b.id} className={voteChoice===b.id?'selected':''} onClick={()=>setVoteChoice(b.id)}><img src={b.cover}/><b>{b.title}</b><span>{b.pages} pages</span></button>)}</div><button className="primary full-button" disabled={!voteChoice} onClick={()=>{if(voteChoice){const next={...activeClub,bookId:voteChoice,phase:'acquiring' as const,status:'Getting copies'};setActiveClub(next);setClubList(prev=>prev.map(c=>c.id===next.id?next:c));setVoteChoice(null)}setVote(false)}}>Submit vote</button></Modal>
 </main>
}
